name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: assigner-react
      DIST: dist
      REGION: ap-south-1
      DIST_ID_CLOUDFRONT: E4GCUWV2L05HY

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Congifigure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.REGION}}


      - name: Install dependencies and build
        run: |
          npm install
          touch .env
          echo VITE_HOST_URL = "https://assigner-api.livetesting.tech" > .env
          echo VITE_MIXPANEL_TOKEN = aa6ae0c89dacc9a19924f4570b7a40bf > .env
          npm run build

      - name: Copy files to S3 storage
        run: |
          aws s3 sync --delete ${{env.DIST}} s3://${{env.BUCKET}}

      - name: Cloudfront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{env.DIST_ID_CLOUDFRONT}} --paths "/*"
